<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AdmTrDocsFiscalR', 'doctrine');

/**
 * BaseAdmTrDocsFiscalR
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_documento
 * @property string $serial_equipo
 * @property integer $reimpresion
 * @property string $numero_comprobante
 * @property timestamp $timestamp
 * @property AdmTrDocs $AdmTrDocs
 * 
 * @method integer          getId()                 Returns the current record's "id" value
 * @method integer          getIdDocumento()        Returns the current record's "id_documento" value
 * @method string           getSerialEquipo()       Returns the current record's "serial_equipo" value
 * @method integer          getReimpresion()        Returns the current record's "reimpresion" value
 * @method string           getNumeroComprobante()  Returns the current record's "numero_comprobante" value
 * @method timestamp        getTimestamp()          Returns the current record's "timestamp" value
 * @method AdmTrDocs        getAdmTrDocs()          Returns the current record's "AdmTrDocs" value
 * @method AdmTrDocsFiscalR setId()                 Sets the current record's "id" value
 * @method AdmTrDocsFiscalR setIdDocumento()        Sets the current record's "id_documento" value
 * @method AdmTrDocsFiscalR setSerialEquipo()       Sets the current record's "serial_equipo" value
 * @method AdmTrDocsFiscalR setReimpresion()        Sets the current record's "reimpresion" value
 * @method AdmTrDocsFiscalR setNumeroComprobante()  Sets the current record's "numero_comprobante" value
 * @method AdmTrDocsFiscalR setTimestamp()          Sets the current record's "timestamp" value
 * @method AdmTrDocsFiscalR setAdmTrDocs()          Sets the current record's "AdmTrDocs" value
 * 
 * @package    sige
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdmTrDocsFiscalR extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('adm_tr_docs_fiscal_r');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_documento', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('serial_equipo', 'string', 128, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 128,
             ));
        $this->hasColumn('reimpresion', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('numero_comprobante', 'string', 128, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 128,
             ));
        $this->hasColumn('timestamp', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AdmTrDocs', array(
             'local' => 'id_documento',
             'foreign' => 'id'));
    }
}