<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AdmMaIdentT', 'doctrine');

/**
 * BaseAdmMaIdentT
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property timestamp $timestamp
 * @property Doctrine_Collection $AdmMaContact
 * @property Doctrine_Collection $AdmMaEmp
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method string              getNombre()       Returns the current record's "nombre" value
 * @method timestamp           getTimestamp()    Returns the current record's "timestamp" value
 * @method Doctrine_Collection getAdmMaContact() Returns the current record's "AdmMaContact" collection
 * @method Doctrine_Collection getAdmMaEmp()     Returns the current record's "AdmMaEmp" collection
 * @method AdmMaIdentT         setId()           Sets the current record's "id" value
 * @method AdmMaIdentT         setNombre()       Sets the current record's "nombre" value
 * @method AdmMaIdentT         setTimestamp()    Sets the current record's "timestamp" value
 * @method AdmMaIdentT         setAdmMaContact() Sets the current record's "AdmMaContact" collection
 * @method AdmMaIdentT         setAdmMaEmp()     Sets the current record's "AdmMaEmp" collection
 * 
 * @package    sige
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdmMaIdentT extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('adm_ma_ident_t');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('timestamp', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('AdmMaContact', array(
             'local' => 'id',
             'foreign' => 'id_tipo_identificacion'));

        $this->hasMany('AdmMaEmp', array(
             'local' => 'id',
             'foreign' => 'id_tipo_identificacion'));
    }
}