<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AdmMaEmpUsersR', 'doctrine');

/**
 * BaseAdmMaEmpUsersR
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_empresa
 * @property integer $id_usuario
 * @property timestamp $timestamp
 * @property AdmMaEmp $AdmMaEmp
 * @property AdmMaUsers $AdmMaUsers
 * 
 * @method integer        getId()         Returns the current record's "id" value
 * @method integer        getIdEmpresa()  Returns the current record's "id_empresa" value
 * @method integer        getIdUsuario()  Returns the current record's "id_usuario" value
 * @method timestamp      getTimestamp()  Returns the current record's "timestamp" value
 * @method AdmMaEmp       getAdmMaEmp()   Returns the current record's "AdmMaEmp" value
 * @method AdmMaUsers     getAdmMaUsers() Returns the current record's "AdmMaUsers" value
 * @method AdmMaEmpUsersR setId()         Sets the current record's "id" value
 * @method AdmMaEmpUsersR setIdEmpresa()  Sets the current record's "id_empresa" value
 * @method AdmMaEmpUsersR setIdUsuario()  Sets the current record's "id_usuario" value
 * @method AdmMaEmpUsersR setTimestamp()  Sets the current record's "timestamp" value
 * @method AdmMaEmpUsersR setAdmMaEmp()   Sets the current record's "AdmMaEmp" value
 * @method AdmMaEmpUsersR setAdmMaUsers() Sets the current record's "AdmMaUsers" value
 * 
 * @package    sige
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdmMaEmpUsersR extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('adm_ma_emp_users_r');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_empresa', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_usuario', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('timestamp', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AdmMaEmp', array(
             'local' => 'id_empresa',
             'foreign' => 'id'));

        $this->hasOne('AdmMaUsers', array(
             'local' => 'id_usuario',
             'foreign' => 'id'));
    }
}