<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AdmTrDocs', 'doctrine');

/**
 * BaseAdmTrDocs
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_empresa
 * @property integer $id_tipo
 * @property string $numero_documento
 * @property integer $id_contacto
 * @property date $fecha_emision
 * @property date $fecha_vencimiento
 * @property decimal $monto_exento
 * @property decimal $monto_gravado
 * @property decimal $monto_impuesto
 * @property decimal $monto_descuento
 * @property string $comentarios
 * @property timestamp $timestamp
 * @property AdmMaDocsT $AdmMaDocsT
 * @property AdmMaEmp $AdmMaEmp
 * @property AdmMaContact $AdmMaContact
 * @property Doctrine_Collection $AdmTrDocsDetalleR
 * @property Doctrine_Collection $AdmTrDocsFiscalR
 * 
 * @method integer             getId()                Returns the current record's "id" value
 * @method integer             getIdEmpresa()         Returns the current record's "id_empresa" value
 * @method integer             getIdTipo()            Returns the current record's "id_tipo" value
 * @method string              getNumeroDocumento()   Returns the current record's "numero_documento" value
 * @method integer             getIdContacto()        Returns the current record's "id_contacto" value
 * @method date                getFechaEmision()      Returns the current record's "fecha_emision" value
 * @method date                getFechaVencimiento()  Returns the current record's "fecha_vencimiento" value
 * @method decimal             getMontoExento()       Returns the current record's "monto_exento" value
 * @method decimal             getMontoGravado()      Returns the current record's "monto_gravado" value
 * @method decimal             getMontoImpuesto()     Returns the current record's "monto_impuesto" value
 * @method decimal             getMontoDescuento()    Returns the current record's "monto_descuento" value
 * @method string              getComentarios()       Returns the current record's "comentarios" value
 * @method timestamp           getTimestamp()         Returns the current record's "timestamp" value
 * @method AdmMaDocsT          getAdmMaDocsT()        Returns the current record's "AdmMaDocsT" value
 * @method AdmMaEmp            getAdmMaEmp()          Returns the current record's "AdmMaEmp" value
 * @method AdmMaContact        getAdmMaContact()      Returns the current record's "AdmMaContact" value
 * @method Doctrine_Collection getAdmTrDocsDetalleR() Returns the current record's "AdmTrDocsDetalleR" collection
 * @method Doctrine_Collection getAdmTrDocsFiscalR()  Returns the current record's "AdmTrDocsFiscalR" collection
 * @method AdmTrDocs           setId()                Sets the current record's "id" value
 * @method AdmTrDocs           setIdEmpresa()         Sets the current record's "id_empresa" value
 * @method AdmTrDocs           setIdTipo()            Sets the current record's "id_tipo" value
 * @method AdmTrDocs           setNumeroDocumento()   Sets the current record's "numero_documento" value
 * @method AdmTrDocs           setIdContacto()        Sets the current record's "id_contacto" value
 * @method AdmTrDocs           setFechaEmision()      Sets the current record's "fecha_emision" value
 * @method AdmTrDocs           setFechaVencimiento()  Sets the current record's "fecha_vencimiento" value
 * @method AdmTrDocs           setMontoExento()       Sets the current record's "monto_exento" value
 * @method AdmTrDocs           setMontoGravado()      Sets the current record's "monto_gravado" value
 * @method AdmTrDocs           setMontoImpuesto()     Sets the current record's "monto_impuesto" value
 * @method AdmTrDocs           setMontoDescuento()    Sets the current record's "monto_descuento" value
 * @method AdmTrDocs           setComentarios()       Sets the current record's "comentarios" value
 * @method AdmTrDocs           setTimestamp()         Sets the current record's "timestamp" value
 * @method AdmTrDocs           setAdmMaDocsT()        Sets the current record's "AdmMaDocsT" value
 * @method AdmTrDocs           setAdmMaEmp()          Sets the current record's "AdmMaEmp" value
 * @method AdmTrDocs           setAdmMaContact()      Sets the current record's "AdmMaContact" value
 * @method AdmTrDocs           setAdmTrDocsDetalleR() Sets the current record's "AdmTrDocsDetalleR" collection
 * @method AdmTrDocs           setAdmTrDocsFiscalR()  Sets the current record's "AdmTrDocsFiscalR" collection
 * 
 * @package    sige
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdmTrDocs extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('adm_tr_docs');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_empresa', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_tipo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('numero_documento', 'string', 128, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 128,
             ));
        $this->hasColumn('id_contacto', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha_emision', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('fecha_vencimiento', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('monto_exento', 'decimal', 10, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 10,
             'scale' => '2',
             ));
        $this->hasColumn('monto_gravado', 'decimal', 10, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 10,
             'scale' => '2',
             ));
        $this->hasColumn('monto_impuesto', 'decimal', 10, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 10,
             'scale' => '2',
             ));
        $this->hasColumn('monto_descuento', 'decimal', 10, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 10,
             'scale' => '2',
             ));
        $this->hasColumn('comentarios', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('timestamp', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AdmMaDocsT', array(
             'local' => 'id_tipo',
             'foreign' => 'id'));

        $this->hasOne('AdmMaEmp', array(
             'local' => 'id_empresa',
             'foreign' => 'id'));

        $this->hasOne('AdmMaContact', array(
             'local' => 'id_contacto',
             'foreign' => 'id'));

        $this->hasMany('AdmTrDocsDetalleR', array(
             'local' => 'id',
             'foreign' => 'id_documento'));

        $this->hasMany('AdmTrDocsFiscalR', array(
             'local' => 'id',
             'foreign' => 'id_documento'));
    }
}