<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AdmMaContactR', 'doctrine');

/**
 * BaseAdmMaContactR
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_contacto
 * @property integer $id_tipo
 * @property timestamp $timestamp
 * @property AdmMaContact $AdmMaContact
 * @property AdmMaContactT $AdmMaContactT
 * 
 * @method integer       getId()            Returns the current record's "id" value
 * @method integer       getIdContacto()    Returns the current record's "id_contacto" value
 * @method integer       getIdTipo()        Returns the current record's "id_tipo" value
 * @method timestamp     getTimestamp()     Returns the current record's "timestamp" value
 * @method AdmMaContact  getAdmMaContact()  Returns the current record's "AdmMaContact" value
 * @method AdmMaContactT getAdmMaContactT() Returns the current record's "AdmMaContactT" value
 * @method AdmMaContactR setId()            Sets the current record's "id" value
 * @method AdmMaContactR setIdContacto()    Sets the current record's "id_contacto" value
 * @method AdmMaContactR setIdTipo()        Sets the current record's "id_tipo" value
 * @method AdmMaContactR setTimestamp()     Sets the current record's "timestamp" value
 * @method AdmMaContactR setAdmMaContact()  Sets the current record's "AdmMaContact" value
 * @method AdmMaContactR setAdmMaContactT() Sets the current record's "AdmMaContactT" value
 * 
 * @package    sige
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdmMaContactR extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('adm_ma_contact_r');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_contacto', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_tipo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('timestamp', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AdmMaContact', array(
             'local' => 'id_contacto',
             'foreign' => 'id'));

        $this->hasOne('AdmMaContactT', array(
             'local' => 'id_tipo',
             'foreign' => 'id'));
    }
}