<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AdmMaEmp', 'doctrine');

/**
 * BaseAdmMaEmp
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property integer $id_tipo_identificacion
 * @property string $numero_identificacion
 * @property integer $id_principal
 * @property timestamp $timestamp
 * @property AdmMaIdentT $AdmMaIdentT
 * @property Doctrine_Collection $AdmMaEmp
 * @property Doctrine_Collection $AdmMaEmpUsersR
 * @property Doctrine_Collection $AdmTrDocs
 * 
 * @method integer             getId()                     Returns the current record's "id" value
 * @method string              getNombre()                 Returns the current record's "nombre" value
 * @method integer             getIdTipoIdentificacion()   Returns the current record's "id_tipo_identificacion" value
 * @method string              getNumeroIdentificacion()   Returns the current record's "numero_identificacion" value
 * @method integer             getIdPrincipal()            Returns the current record's "id_principal" value
 * @method timestamp           getTimestamp()              Returns the current record's "timestamp" value
 * @method AdmMaIdentT         getAdmMaIdentT()            Returns the current record's "AdmMaIdentT" value
 * @method Doctrine_Collection getAdmMaEmp()               Returns the current record's "AdmMaEmp" collection
 * @method Doctrine_Collection getAdmMaEmpUsersR()         Returns the current record's "AdmMaEmpUsersR" collection
 * @method Doctrine_Collection getAdmTrDocs()              Returns the current record's "AdmTrDocs" collection
 * @method AdmMaEmp            setId()                     Sets the current record's "id" value
 * @method AdmMaEmp            setNombre()                 Sets the current record's "nombre" value
 * @method AdmMaEmp            setIdTipoIdentificacion()   Sets the current record's "id_tipo_identificacion" value
 * @method AdmMaEmp            setNumeroIdentificacion()   Sets the current record's "numero_identificacion" value
 * @method AdmMaEmp            setIdPrincipal()            Sets the current record's "id_principal" value
 * @method AdmMaEmp            setTimestamp()              Sets the current record's "timestamp" value
 * @method AdmMaEmp            setAdmMaIdentT()            Sets the current record's "AdmMaIdentT" value
 * @method AdmMaEmp            setAdmMaEmp()               Sets the current record's "AdmMaEmp" collection
 * @method AdmMaEmp            setAdmMaEmpUsersR()         Sets the current record's "AdmMaEmpUsersR" collection
 * @method AdmMaEmp            setAdmTrDocs()              Sets the current record's "AdmTrDocs" collection
 * 
 * @package    sige
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdmMaEmp extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('adm_ma_emp');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('id_tipo_identificacion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('numero_identificacion', 'string', 128, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 128,
             ));
        $this->hasColumn('id_principal', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('timestamp', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AdmMaIdentT', array(
             'local' => 'id_tipo_identificacion',
             'foreign' => 'id'));

        $this->hasMany('AdmMaEmp', array(
             'local' => 'id',
             'foreign' => 'id_principal'));

        $this->hasMany('AdmMaEmpUsersR', array(
             'local' => 'id',
             'foreign' => 'id_empresa'));

        $this->hasMany('AdmTrDocs', array(
             'local' => 'id',
             'foreign' => 'id_empresa'));
    }
}