<?php

/**
 * AdmMaContactRTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdmMaContactRTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdmMaContactRTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdmMaContactR');
    }
}