<?php

/**
 * AdmMaItemsTTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdmMaItemsTTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdmMaItemsTTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdmMaItemsT');
    }
}