<?php

/**
 * AdmMaItemsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdmMaItemsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdmMaItemsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdmMaItems');
    }
}