<?php

/**
 * AdmMaEmpUsersRTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdmMaEmpUsersRTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdmMaEmpUsersRTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdmMaEmpUsersR');
    }
}