<?php

/**
 * AdmMaTaxTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdmMaTaxTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdmMaTaxTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdmMaTax');
    }
}