<?php

/**
 * AdmMaEmpTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdmMaEmpTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdmMaEmpTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdmMaEmp');
    }
}