<?php

/**
 * AdmMaUsersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdmMaUsersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdmMaUsersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdmMaUsers');
    }
}