<?php

/**
 * AdmMaIdentTTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdmMaIdentTTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdmMaIdentTTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdmMaIdentT');
    }
}