<?php

/**
 * AdmTrDocsTTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdmTrDocsTTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdmTrDocsTTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdmTrDocsT');
    }
}