<?php

/**
 * AdmTrDocsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdmTrDocsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdmTrDocsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdmTrDocs');
    }
}