<?php

/**
 * AdmTrDocsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */ 
class AdmTrDocsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdmTrDocsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdmTrDocs');
    }


    public static function getSumRenglones($id)
    {
      $renglones = Doctrine_Query::create()
        ->from('AdmTrDocsDetalleR a')
        ->where('a.id_documento = ?', $id)->execute();

      $acu_impuesto = $acu_gravado = $acu_exento = 0;

      foreach( $renglones as $renglon){
        $acu_impuesto += $renglon->getMontoImpuesto();

        if( $renglon->getMontoImpuesto() > 0 ) {
          $acu_gravado += $renglon->getPrecio() * $renglon->getCantidad();
        } else if( $renglon->getMontoImpuesto() == 0 ) {
          $acu_exento  += $renglon->getPrecio() * $renglon->getCantidad();
        }

      }

      return array(
        "acu_impuesto" => $acu_impuesto,
        "acu_gravado"  => $acu_gravado,
        "acu_exento"   => $acu_exento
        );
    }      

    public static function TotalDocumentos(){
        $q = Doctrine_Query::create()
            ->select("*")
            ->addSelect("(monto_exento + monto_gravado + monto_impuesto) as total_documento")
            ->from("AdmTrDocs a");
        return $q;
    }

}