<?php

/**
 * AdmTrDocsDetalleRTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdmTrDocsDetalleRTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdmTrDocsDetalleRTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdmTrDocsDetalleR');
    }
}