<?php

/**
 * AdmTrDocs
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sige
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class AdmTrDocs extends BaseAdmTrDocs
{
	public function save (Doctrine_Connection $con = null)
	{
	   return parent::save($con);
	}

	public function actualizarAcumulados()
	{
	   $renglon = $this->getTable()->getSumRenglones($this->getId());
	   $this->setMontoImpuesto  ( $renglon["acu_impuesto"] );
	   $this->setMontoGravado	( $renglon["acu_gravado"]  );
	   $this->setMontoExento	( $renglon["acu_exento"]   );
	}
}
