AdmMaContact:
  connection: doctrine
  tableName: adm_ma_contact
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nombre:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    tipo_contacto:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '1'
      notnull: true
      autoincrement: false
    id_tipo_identificacion:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    numero_identificacion:
      type: string(128)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    direccion:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    telefonos:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    email:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    exonerado:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
    jubilado:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
    timestamp:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    AdmMaIdentT:
      local: id_tipo_identificacion
      foreign: id
      type: one
    AdmMaContactR:
      local: id
      foreign: id_contacto
      type: many
    AdmMaUsers:
      local: id
      foreign: id_contacto
      type: many
    AdmTrDocs:
      local: id
      foreign: id_contacto
      type: many
AdmMaContactR:
  connection: doctrine
  tableName: adm_ma_contact_r
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    id_contacto:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    id_tipo:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    timestamp:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    AdmMaContact:
      local: id_contacto
      foreign: id
      type: one
    AdmMaContactT:
      local: id_tipo
      foreign: id
      type: one
AdmMaContactT:
  connection: doctrine
  tableName: adm_ma_contact_t
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nombre:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    modulo:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    timestamp:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    AdmMaContactR:
      local: id
      foreign: id_tipo
      type: many
AdmMaDocsT:
  connection: doctrine
  tableName: adm_ma_docs_t
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nombre:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    modulo:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    origen:
      type: string(50)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    tipo_fiscal:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
    afecta_cuentas:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
    signo_cuentas:
      type: string(1)
      fixed: false
      unsigned: false
      primary: false
      default: +
      notnull: true
      autoincrement: false
    contiene_renglones:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
    afecta_inventario:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
    reserva_inventario:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
    signo_inventario:
      type: string(1)
      fixed: false
      unsigned: false
      primary: false
      default: +
      notnull: true
      autoincrement: false
    id_cuenta:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    activo:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '1'
      notnull: true
      autoincrement: false
    timestamp:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    AdmTrDocs:
      local: id
      foreign: id_tipo
      type: many
AdmMaEmp:
  connection: doctrine
  tableName: adm_ma_emp
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nombre:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    id_tipo_identificacion:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    numero_identificacion:
      type: string(128)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    id_principal:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    timestamp:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    AdmMaIdentT:
      local: id_tipo_identificacion
      foreign: id
      type: one
    AdmMaEmp:
      local: id
      foreign: id_principal
      type: many
    AdmMaEmpUsersR:
      local: id
      foreign: id_empresa
      type: many
    AdmTrDocs:
      local: id
      foreign: id_empresa
      type: many
AdmMaEmpUsersR:
  connection: doctrine
  tableName: adm_ma_emp_users_r
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    id_empresa:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    id_usuario:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    timestamp:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    AdmMaEmp:
      local: id_empresa
      foreign: id
      type: one
    AdmMaUsers:
      local: id_usuario
      foreign: id
      type: one
AdmMaIdentT:
  connection: doctrine
  tableName: adm_ma_ident_t
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nombre:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    timestamp:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    AdmMaContact:
      local: id
      foreign: id_tipo_identificacion
      type: many
    AdmMaEmp:
      local: id
      foreign: id_tipo_identificacion
      type: many
AdmMaItems:
  connection: doctrine
  tableName: adm_ma_items
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    id_tipo:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    nombre:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    costo:
      type: 'decimal(10, 2)'
      fixed: false
      unsigned: false
      primary: false
      default: '0.00'
      notnull: true
      autoincrement: false
    precio:
      type: 'decimal(10, 2)'
      fixed: false
      unsigned: false
      primary: false
      default: '0.00'
      notnull: true
      autoincrement: false
    id_impuesto:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    timestamp:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    AdmMaItemsT:
      local: id_tipo
      foreign: id
      type: one
    AdmMaTax:
      local: id_impuesto
      foreign: id
      type: one
    AdmTrDocsDetalleR:
      local: id
      foreign: id_items
      type: many
AdmMaItemsT:
  connection: doctrine
  tableName: adm_ma_items_t
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nombre:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    timestamp:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    AdmMaItems:
      local: id
      foreign: id_tipo
      type: many
AdmMaTax:
  connection: doctrine
  tableName: adm_ma_tax
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nombre:
      type: string(128)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    alias:
      type: string(64)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    porcentaje:
      type: 'decimal(6, 2)'
      fixed: false
      unsigned: false
      primary: false
      default: '0.00'
      notnull: true
      autoincrement: false
    timestamp:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    AdmMaItems:
      local: id
      foreign: id_impuesto
      type: many
AdmMaUsers:
  connection: doctrine
  tableName: adm_ma_users
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    username:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    password:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    id_contacto:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    activo:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '1'
      notnull: true
      autoincrement: false
    timestamp:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    AdmMaContact:
      local: id_contacto
      foreign: id
      type: one
    AdmMaEmpUsersR:
      local: id
      foreign: id_usuario
      type: many
AdmTrDocs:
  connection: doctrine
  tableName: adm_tr_docs
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    id_empresa:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    id_tipo:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    numero_documento:
      type: string(128)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    id_contacto:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    fecha_emision:
      type: date(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    fecha_vencimiento:
      type: date(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    monto_exento:
      type: 'decimal(10, 2)'
      fixed: false
      unsigned: false
      primary: false
      default: '0.00'
      notnull: true
      autoincrement: false
    monto_grabado:
      type: 'decimal(10, 2)'
      fixed: false
      unsigned: false
      primary: false
      default: '0.00'
      notnull: true
      autoincrement: false
    monto_impuesto:
      type: 'decimal(10, 2)'
      fixed: false
      unsigned: false
      primary: false
      default: '0.00'
      notnull: true
      autoincrement: false
    monto_descuento:
      type: 'decimal(10, 2)'
      fixed: false
      unsigned: false
      primary: false
      default: '0.00'
      notnull: true
      autoincrement: false
    comentarios:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    timestamp:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    AdmMaDocsT:
      local: id_tipo
      foreign: id
      type: one
    AdmMaEmp:
      local: id_empresa
      foreign: id
      type: one
    AdmMaContact:
      local: id_contacto
      foreign: id
      type: one
    AdmTrDocsDetalleR:
      local: id
      foreign: id_documento
      type: many
    AdmTrDocsFiscalR:
      local: id
      foreign: id_documento
      type: many
AdmTrDocsDetalleR:
  connection: doctrine
  tableName: adm_tr_docs_detalle_r
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    id_documento:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    id_items:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    descripcion:
      type: string(256)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    cantidad:
      type: 'decimal(10, 3)'
      fixed: false
      unsigned: false
      primary: false
      default: '0.000'
      notnull: true
      autoincrement: false
    costo:
      type: 'decimal(10, 2)'
      fixed: false
      unsigned: false
      primary: false
      default: '0.00'
      notnull: true
      autoincrement: false
    precio:
      type: 'decimal(10, 2)'
      fixed: false
      unsigned: false
      primary: false
      default: '0.00'
      notnull: true
      autoincrement: false
    monto_impuesto:
      type: 'decimal(10, 2)'
      fixed: false
      unsigned: false
      primary: false
      default: '0.00'
      notnull: true
      autoincrement: false
    alias_impuesto:
      type: string(128)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    timestamp:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    AdmTrDocs:
      local: id_documento
      foreign: id
      type: one
    AdmMaItems:
      local: id_items
      foreign: id
      type: one
AdmTrDocsFiscalR:
  connection: doctrine
  tableName: adm_tr_docs_fiscal_r
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    id_documento:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    serial_equipo:
      type: string(128)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    reimpresion:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
    numero_comprobante:
      type: string(128)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    timestamp:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    AdmTrDocs:
      local: id_documento
      foreign: id
      type: one
